config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'meetings#welcome'
  resources :meetings
  get '/all', to: 'meetings#all'
  get '/calendar', to: 'meetings#index'
  get 'users/:id', to: 'users#show', as: :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :meetings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_account_update_params, if: :devise_controller?
  before_filter :set_time_zone, if: :user_signed_in?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

  private

  def set_time_zone
    Time.zone = current_user.time_zone
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!, except: [:welcome]
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  def index
    @meetings = Meeting.where("user_id = #{current_user.id}")
  end

  # GET /meetings/1
  def show
    @meeting = Meeting.find(params[:id])
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  def create
    @meeting = current_user.meetings.new(meeting_params)
    if @meeting.save
      redirect_to @meeting, notice: 'Created event.'
    else
      render :new
    end
  end

  # PATCH/PUT /meetings/1
  def update
    if @meeting.update(meeting_params)
      redirect_to @meeting, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /meetings/1
  def destroy
    @meeting.destroy
      redirect_to meetings_url, notice: 'Event was successfully destroyed.'
  end

  def welcome
  end

  def all
    @meetings = Meeting.where("user_id = #{current_user.id}")
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meeting_params
    params.require(:meeting).permit(:name, :start_time, :end_time)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'meetings/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(meeting) do |f| %>
    <% if meeting.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
          <ul>
            <% meeting.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :start_time %>
      <%= f.text_field :start_time, class: 'form-control' %>
    </div>

    <div class="field">
      <%= f.label :end_time %>
      <%= f.text_field :end_time, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit class: 'btn btn-lg btn-success' %>
      <%= link_to 'Back', '/calendar', class: 'btn btn-lg btn-info' %>
    </div>
<% end %>

app/views/meetings/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" style="border-radius: 0px;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/calendar">Event Calendar</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_page?(new_meeting_path) %>
            <li class="active"><a href="../meetings/new">Create new event</a></li>
        <% else %>
            <li><a href="../meetings/new">Create new event</a></li>
        <% end %>
        <% if current_page?(meetings_path) %>
          <li class="active"><a href="../all">My events</a></li>
        <% else %>
            <li><a href="../all">My events</a></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <% if current_user.first_name == "" && current_user.last_name == "" %>
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"> My account <b class="caret"></b></a>
              <% else %>
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %> <%= current_user.last_name %> <b class="caret"></b></a>
              <% end %>
              <ul class="dropdown-menu">
                <li><%=link_to "Profile", user_path(current_user)%></li>
                <li class="divider"></li>
                <li><%=link_to "Sign out", destroy_user_session_path, method:"delete"%></li>
              </ul>
            </li>
        <% else %>
            <% if current_page?(new_user_session_path) %>
                <li class="active"><%=link_to 'Sign in', new_user_session_path %></li>
            <% else %>
                <li><%=link_to 'Sign in', new_user_session_path%></li>
            <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/meetings/all.html.erb
<div class="panel panel-default panel-body">
  <h3>My events</h3>

  <table class="table table-striped">
    <% @meetings.each do |meeting| %>
        <tr>
          <td><%= meeting.name %></td>
          <td><%= meeting.start_time %></td>
          <td><%= link_to 'Details', meeting %></td>
          <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
          <td><%= link_to 'Delete', meeting, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
  </table>
  <br>
  <%= link_to 'New Meeting', new_meeting_path, class: "btn btn-default" %>
</div>

app/views/meetings/edit.html.erb
<div class="container">
  <div class="form-signin">
    <div class="panel panel-default panel-body">
      <h1>Editing event</h1>
      <%= render 'form', meeting: @meeting %>
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= month_calendar events: @meetings do |date, meetings| %>
        <%= date.day %>
        <br>
          <% meetings.each do |meeting| %>
              <p><%= link_to meeting.name, meeting %></p>
          <% end %>
    <% end %>
  </div>
</div>

app/views/meetings/new.html.erb
<div class="container">
  <div class="form-signin">
    <div class="panel panel-default panel-body">
      <h1>Creating event</h1>
      <%= render 'form', meeting: @meeting %>
    </div>
  </div>
</div>

app/views/meetings/show.html.erb
<div class="container">
  <div class="form-signin">
    <div class="panel panel-default panel-body">
      <h1><%= @meeting.name %></h1>
      <br>
      <strong>Start time:</strong>
      <p class="bg-warning">
        <%= @meeting.start_time %>
      </p>

      <strong>End time:</strong>
      <p class="bg-warning">
        <%= @meeting.end_time %>
      </p>
      <br>
      <%= link_to 'Edit', edit_meeting_path(@meeting), class: 'btn btn-lg btn-success' %>
      <%= link_to 'Back', meetings_path, class: 'btn btn-lg btn-info' %>
    </div>
  </div>
</div>

app/views/meetings/welcome.html.erb
<h1 style="text-align: center">Welcome!</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-5">
    <a href="/calendar" class="btn btn-lg btn-default">Calendar</a>
    <a href="/users/sign_up" class="btn btn-lg btn-default">Sign up</a>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <h2 class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '<'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '>'), calendar.url_for_next_view %>
  </h2>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="form-signin">
    <div class="panel panel-default panel-body">
      <h1 class="form-signin-heading">Profile</h1>
      <br>
      <div class="field">
        <p><strong>Name:</strong> <%= @user.first_name %> <%= @user.last_name %> </p>
      </div>

      <div class="field">
        <p><strong>Email:</strong> <%= @user.email %></p>
      </div>
      <br>
        <%= link_to 'Edit profile data', '/users/edit', class:"btn btn-lg btn-info" %>
        <%= link_to 'Back', '/calendar', class: "btn btn-lg btn-default" %>


    </div>
  </div>
</div>